### ISSUE TITLE
[Feature] Support for OMV 6 (Shaitan)

### ISSUE THREAD

**Issue by mohyat** [tomaae/homeassistant-openmediavault#50]
## Describe the issue

Not working after upgrade to 6.0-20 (Shaitan)

## How to reproduce the issue

Just clean install of latest omv 6.0-20 (Shaitan)

## Screenshots

Here is error in HA:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/openmediavault/__init__.py", line 23, in async_setup_entry
    await controller.async_hwinfo_update()
  File "/config/custom_components/openmediavault/omv_controller.py", line 112, in async_hwinfo_update
    await self.hass.async_add_executor_job(self.get_hwinfo)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmediavault/omv_controller.py", line 171, in get_hwinfo
    tmp = self.data["hwinfo"]["uptime"].split(" ")
AttributeError: 'float' object has no attribute 'split'
```

## Software versions

 - Home Assistant version: 
 - openmediavault integration version: 
 - openmediavault software version: 

Home Assistant version: 2021.7.4
openmediavault integration version: 1.1.7
openmediavault software version: 6.0-20 (Shaitan)

**Comment by tomaae** [comment]
Yea, I didnt expect OMV to keep consistency with new version as usual, that was one of reasons why I decided to step away from OMV.
I have no plan add OMV 6 support at the moment. If someone else wants to, I will help as much as I can.
I may add it myself if I get a hold of machine where I can install OMV temporarily, since it does not want to boot in my VM.

**Comment by Yannik25** [comment]
Hi, I just created a Pull Request: #55.
With this PR OMV 5.6 as well as 6.22 is working again.

**Comment by tomaae** [comment]
thanks, merged

**Comment by LanceMcCarthy** [comment]
Although I do not see any errors in the core logs, the integrations doesn't appear in the HA Integrations list:

![image](https://user-images.githubusercontent.com/3520532/134262616-0af4bf65-6acc-4c18-aef0-e52b8a660da2.png)

> I did restart Core a few times just to make sure it wasn't 

Details on Home Assistant OS (running on Home Assistant Blue / Odroid N2+):

![image](https://user-images.githubusercontent.com/3520532/134262650-b9954758-39c5-402d-a940-53ff6900e2ed.png)

**Comment by LanceMcCarthy** [comment]
Sorry, disregard. I needed to reboot the host. Just restarting Home Assistant didn't work.
